# Generated by Django 3.0.2 on 2020-01-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='link_to',
            new_name='url_to',
        ),
    ]
