# Generated by Django 3.0.2 on 2020-01-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20200117_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='author',
        ),
    ]
