# Generated by Django 3.0.2 on 2020-01-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_submission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
